### ISSUE TITLE
video playback

### ISSUE THREAD

**Issue by Dabbiedabdab** [aashishksahu/SafeSpace#100]
If I click a video from the gallery overview the video won't play. (No length showing either)
If I then swipe to the next video and back the first video plays without an issue.

**Comment by aashishksahu** [comment]
Hi @Dabbiedabdab can you please list down the steps to reproduce this issue?
1. How did you reach this point of failure
2. what video format is it
3. Does it happen when the app is restarted or after coming back to the list from the gallery and then going back?
