### ISSUE TITLE
Why is the key changed?

### ISSUE THREAD

**Issue by linsui** [aashishksahu/SafeSpace#13]
Is it lost?

**Comment by aashishksahu** [comment]
Unfortunately, yes :(

**Comment by linsui** [comment]
Maybe you'd like to take a look at our post https://f-droid.org/en/2023/09/03/reproducible-builds-signing-keys-and-binary-repos.html. :)

**Comment by aashishksahu** [comment]
I read the article, I have added notes in the release and will also explain here what happened. 

So, it was actually quite dumb, but I really have a bad habit of using Shift+delete, I keep doing it and I keep regretting it. This was my first FOSS project that I did all on my own and then I screwed up by again using shift+delete on my desktop where I was trying to delete other files and the Android studio projects folder was also there. As of now, I have completely disabled the shortcut on all of my Windows devices and have taken multiple backups of the key store. 

I honestly didn't know that changing these keys would prevent the app from updating. I thought that these keys were just to authenticate who the developer is. 
I guess... lessons were learnt the hard way... 
I will keep this issue open just in case anybody needs clarification on why they can't update their app.  

Once again, apologies to the users of my app. 😔

Affected release: v1.1.3

**Comment by linsui** [comment]
https://gitlab.com/fdroid/fdroiddata/-/commit/4cda106de8453e98c81ae1ba03468e6f5fea3976 Updated. Thanks for you detailed notes. :)

**Comment by IzzySoft** [comment]
So do we have a way of verification, as outlined in the linked article?

* your old key is lost, so you cannot sign a copy with it to check against
* your commits are not signed (the only signed commits have used Github's key as they seem to be made via the Github WebUI). I strongly suggest you signing commits with your own GPG/PGP key.
* I see no other contributor here who can vouch for you

Any of the other option available?

**Comment by aashishksahu** [comment]
Hi @IzzySoft 
I may not have much but I have a few commits on the master branch that I did using github web ui with my own account (2FA is enabled), the commits are as follows: 

The very first commit: 
[03454af773ed75a2bb9a5269a6601653d94a764b](https://github.com/aashishksahu/SafeSpace/commit/03454af773ed75a2bb9a5269a6601653d94a764b)

Somewhere in between:
[ec6ca5f2a800f0a1ec590cf437dd3550b14ed9fd](https://github.com/aashishksahu/SafeSpace/commit/ec6ca5f2a800f0a1ec590cf437dd3550b14ed9fd)

This is the current release
[7b2441525722487a57df6abafa28b573dc5087fb](https://github.com/aashishksahu/SafeSpace/commit/7b2441525722487a57df6abafa28b573dc5087fb)

Unlike the other commits done using android studio, these were done using my github account and have the verified tag, hopefully this can help.

**Comment by IzzySoft** [comment]
> with my own account (2FA is enabled)

That is a good point indeed (2FA enabled makes a "hack-in" much less likely, especially for committing via the WebUI). Anyone knows how one can verify that "some other account" (other than one's own) has 2FA enabled? I know one can check it [for users of one's own organization](https://docs.github.com/de/organizations/keeping-your-organization-secure/managing-two-factor-authentication-for-your-organization/viewing-whether-users-in-your-organization-have-2fa-enabled), but not how to check that for **any other** account.

**Comment by linsui** [comment]
@IzzySoft It doesn't make sense anymore. You need to go back in time to check that it was enabled.

**Comment by aashishksahu** [comment]
Yes, there's no time stamp for when I enabled 2FA (but I did enable it long ago). Based on [this article](https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa), 2fa seems mandatory to enable to push commits.

**Comment by IzzySoft** [comment]
> Based on [this article](https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa), 2fa seems mandatory to enable to push commits.

Where exactly does it say so? All I see there is, quote (emphasis mine):

> **Starting in March 2023 and through the end of 2023**, GitHub will **gradually begin** to require all users who contribute code on GitHub.com to enable one or more forms of two-factor authentication (2FA). If you are in an **eligible group**, you will receive a notification email when that group is selected for enrollment, marking the beginning of a 45-day 2FA enrollment period, and you will see banners asking you to enroll in 2FA on GitHub.com. **If you don't receive a notification, then you are not part of a group required to enable 2FA, though we strongly recommend it.**

Note: "gradually begin", "eligible group", the time frame going until end of the year – and the fact not all accounts are affected. So as @linsui pointed out: unless we have a way to verify 2FA was continually enabled at least since the last release with the "old key", we cannot use that as means of verification.

**Comment by aashishksahu** [comment]
Yeah I thought so too. There's no legitimate way of verifying when 2fa was enabled.

**Comment by IzzySoft** [comment]
So any chance for one of the other methods? Independent from that: please consider establishing one or more from the precautions now, just in case: signing your commits with your own GPG/PGP key, providing an alternative method of contact (XMPP, Threema, Signal, Matrix, …), naming (a) person(s) who can vouch for you as they have personal contact with you (in person or via an alternative, secure contact method) – or whatever other ideas might exist.

**Comment by aashishksahu** [comment]
I have setup gpg signing for my account and will be signing my commits from now on, will also add my email as a mode of contact. Apart from that, since there is not much available on the suggested methods of verification, will it be possible for some kind of code comparison or security analysis to prove that the repository does not contain any malicious code? 

Also, I use the github mobile app as 2fa method, I can share the screenshot of when the app was installed and a screenshot indicating 2fa is enabled, will that work (I know this sounds absurd but just trying) ?

**Comment by IzzySoft** [comment]
I'd say that would be better than nothing. Should the screenshot contain sensible details, you could provide it via a confidential issue at fdroiddata (linking from it to here for reference). @linsui what would you say?

And good you will sign commits from now on, a big :+1: for that! Take good care of both keys then :wink:

**Comment by aashishksahu** [comment]
I have opened an issue on fdroiddata: [#3080](https://gitlab.com/fdroid/fdroiddata/-/issues/3080)

**Comment by IzzySoft** [comment]
Thanks! I've left a comment there.

**Comment by GameOverFlowChart** [comment]
> I honestly didn't know that changing these keys would prevent the app from updating. I thought that these keys were just to authenticate who the developer is. I guess... lessons were learnt the hard way... I will keep this issue open just in case anybody needs clarification on why they can't update their app.

That's part of the security. Imagine criminals wants to steal my files stored in the app. They could fork your app, make a version that sends the private files to them and trick me into installing it. Well they can't. Because they don't have your key. But I'm glad that the problem with adding whole folder structures prevented me from using the app (creating folders manually is a lot of work). So I could simply uninstall it without losing data (I had only test files in it).

**Comment by aashishksahu** [comment]
@GameOverFlowChart Yeah the security thing makes sense. Btw, you can import zips in the app, so you won't need to create each folder manually. Please give it a shot :)
