### ISSUE TITLE
Support unzipping Zip files

### ISSUE THREAD

**Issue by GameOverFlowChart** [aashishksahu/SafeSpace#16]
So this is related to #6 

Your new feature with the zip backup gave me the idea. If the app already has code to unzip zip files, you could give the option to unzip zip files inside safespace. This way I could zip my folder structure, bring that zip into safespace (since it's a single file now) and unzip it there.

**Comment by aashishksahu** [comment]
Yeah, this already works. The zips you import can be from anywhere, not necessarily the exported backup from the app :)

**Comment by GameOverFlowChart** [comment]
Oh nice, I had tried to put a zip into the safe space but that way it didn't know what to do with it. I will test this the upcoming days.

**Comment by aashishksahu** [comment]
@GameOverFlowChart you need to import the zip from the 3 dots menu.

**Comment by bloodyeyesblackblood** [comment]
> Yeah, this already works. The zips you import can be from anywhere, not necessarily the exported backup from the app :)
> 
> In case you face any issues importing a zip, please feel free to add the details here.

are there any plans to include support for .7z or other formats?
or is it better to store files on mobile in zip instead of .7z anyways?

**Comment by aashishksahu** [comment]
@bloodyeyesblackblood The zip format is widely supported on android phones and a lot of phones don't support 7z and tar support is much rarer. So from that perspective I thought to go with zip, and zip does the job, so no plans of including 7z and tar as of now :)
