### ISSUE TITLE
does not ask for pattern

### ISSUE THREAD

**Issue by Klimmbimmel** [aashishksahu/SafeSpace#17]
After I press the "login", it tells me, that I don't use a security mechanism ("No Biometric or PIN set"). But I do have a pattern, which is asked by the browser for example.

Android 10
LineageOS
Current version from F-Droid, 1.1.5

**Comment by aashishksahu** [comment]
@Klimmbimmel This is really weird. If you have enabled the system pin/pattern then it should show up. Are you sure you're not using some other kind of authentication instead of the one built-in to android.

**Comment by aashishksahu** [comment]
It's a weird scenario, it would really be difficult to replicate this.

**Comment by aashishksahu** [comment]
@Klimmbimmel That would be very helpful, please let me know if it works on a different phone. So far I haven't seen any case where system lock doesn't work because it's a built-in functionality. All the phones I have in my friends & family have the lock working for them.

**Comment by aashishksahu** [comment]
I think it should work irrespective of whether you use a pin/password/pattern. It works for me on pixel experience with Android 13.

**Comment by atikattar1104** [comment]
Redmi 7A User Here, MIUI 12.5. Same Thing Happens. Using System Built-In Lock. But App Says "No Biometric Or PIN Set".

**Comment by atikattar1104** [comment]
I Saw The Code Of `AuthActivity.kt`. It Seems Like The Methods Of Calling The System Authentication Only Works On Latest Android OSes. Try Adding Older Or Deprecated Methods Of The Same. Probably This Should Fix This Problem.

**Comment by atikattar1104** [comment]
Just Tried With Other Types Of System Provided Locking Mechanisms, Still The Same Errors.

**Comment by aashishksahu** [comment]
Hi @atikattar1104 Thank you for taking the time to check out the code, much appreciated. My app is using Biometric Manager which is supported by phones running android 10 and above, since MIUI 12.5 is based on android 11, biometric manager should work. Maybe Xiaomi uses it's own api for authentication and does not use biometric manager (just maybe...). Nevertheless, I've been working on an update which will now show a reason for why authentication is not working, please try this test [apk](https://github.com/aashishksahu/SafeSpace/blob/22_-adding-functions/app/release/app-release.apk) and let me know if this helps, you can post the reason here so I can check further, if you'd like to work on this issue, that would also be great. Thanks :)

**Comment by atikattar1104** [comment]
Hi @aashishksahu. Just Tried The APK You Mentioned. This Is The Error It Shows. :- 

![Screenshot_2023-12-25-21-12-41-829_org privacymatters safespace](https://github.com/aashishksahu/SafeSpace/assets/93785261/fd956996-7cb9-4429-9a5a-1a7d68fbfde3)

For Context, I Have A Password-Based Screen Lock (QWERTY Keyboard Based) With Fingerprint Not Supported. I Have Face Recognition Support Though.

**Comment by atikattar1104** [comment]
Hey There, Just Tried To Understand The Code, I Honestly Don't Know How Kotlin Works. But From My Understanding, This Might Be The Code Block That Might Be The Reason For This Error. :- 

![Screenshot_2023-12-25-21-29-29-756_com android chrome](https://github.com/aashishksahu/SafeSpace/assets/93785261/24aff315-fc95-46dc-99d0-5654dd0d8d2b)

I Guess The `when` Code Block Is The Reason.

The Errors Are Being Called When Biometric Manager CAN Authenticate Using Device Credentials. Where The Code Should Have Conditional Mechanism For Checking Whether Biometric Manager `Can Or Cannot` Authenticate Using Device Credentials.

I Think That May Be The Reason Why This Occurs, But Again, I Don't Know How Kotlin Works. So, In Case This Might Not Be The Reason For This Issue, I Apologize In Advance😅.

Thanks!

**Comment by aashishksahu** [comment]
Yes you are pointing to the right code, although this is from the main branch which is yet to be updated. The apk you used just now is from the feature branch, which is updated. As for Kotlin, it's just java with a lot of syntax sugar. You can learn it easily if you already know Java.

**Comment by atikattar1104** [comment]
Thanks! I Will Try Learning Kotlin. 

You Are Right About The Xiaomi API. MIUI Does Not Use `biometricmanager` Class To Authenticate With System Authentication Mechanism.

Although I Asked Llama2 For The Help, He Suggested To Use `AuthenticationManager` Class, Which Is Compatible For Xiaomi And Newer Android Devices, And Also Gave Me A Sample Code For The Same. Here's It's Response :- 

 I understand. In that case, you can use the `AuthenticationManager` class provided by the Android framework to implement a system-level authentication mechanism.

Here's an example of how you could use `AuthenticationManager` to implement a simple authentication flow:

1. First, you'll need to create an `Authenticator` object that will handle the actual authentication process. This object should contain a reference to the `AuthenticationManager` and should override the `authenticate()` method:
```
import android.content.Context;
import android.security.auth.AuthenticationManager;

public class MyAuthenticator implements Authenticator {
    private final AuthenticationManager mAuthManager;

    public MyAuthenticator(Context context) {
        mAuthManager = (AuthenticationManager) context.getSystemService(Context.AUTHENTICATION_SERVICE);
    }

    @Override
    public boolean authenticate(String credential) {
        // Implement your authentication logic here
        // For example, you could use a password or a fingerprint scanner
        // to authenticate the user
        return true; // Return true if authentication was successful
    }
}
```
1. Next, you'll need to create a `BroadcastReceiver` that will listen for the `ACTION_AUTHENTICATE` action and launch the authentication flow:
```
import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.Intent;

public class AuthReceiver extends BroadcastReceiver {
    @Override
    public void onReceive(Context context, Intent intent) {
        if (intent.getAction().equals(AuthenticationManager.ACTION_AUTHENTICATE)) {
            MyAuthenticator auth = new MyAuthenticator(context);
            auth.authenticate();
        }
    }
}
```
1. Then, you'll need to register the `BroadcastReceiver` in your app's manifest file:
```
<receiver android:name=".AuthReceiver">
    <intent-filter>
        <action android:name="android.security.auth.AuthenticationManager.ACTION_AUTHENTICATE" />
    </intent-filter>
</receiver>
```
1. Finally, you can trigger the authentication flow by sending a broadcast intent with the `ACTION_AUTHENTICATE` action:
```
Intent intent = new Intent(AuthenticationManager.ACTION_AUTHENTICATE);
sendBroadcast(intent);
```
When the authentication flow completes, the `MyAuthenticator` class will receive the result of the authentication attempt through the `authenticate()` method. If the authentication was successful, the method will return `true`, and you can use this result to unlock your app.

Note that this is just a basic example, and you'll likely need to modify it to fit your specific use case. Additionally, you'll need to ensure that your app has the necessary permissions to use the `AuthenticationManager` service.

Hope This Helps,

Thanks!

**Comment by aashishksahu** [comment]
Thanks for this! Will check it out. AI is serious though 😅

**Comment by aashishksahu** [comment]
@atikattar1104 Apparently, `AuthenticationManager` is a class in Spring Framework and there's nothing in android sdk with a similar name. I tried importing `android.security.auth.AuthenticationManager` but I got class not found. This reminded me of [‘confidently incorrect AI'](https://www.theregister.com/2023/08/07/chatgpt_stack_overflow_ai/) problem and how AI can appear so confident even though it's incorrect. Anyway, on the bright side, we still keep our jobs, lol :)

**Comment by atikattar1104** [comment]
DAMN! I Didn't Knew About This AI Glitch. I Was Genuinely Convinced By AI. I Always Thought AI Cannot Lie. I Think It Is Better To Stick To The Original Source, The Internet.

Currently I Am Busy Because Of My Exams. So, Maybe I Will Be Able To Help In This After Upcoming 5th Of Jan. In The Meantime, If I Get Some Time I Will Let You Know About Any Other Ways To Implement A Solution To This.

**Comment by aashishksahu** [comment]
@atikattar1104 best of luck for your exams :)

**Comment by Tvirin** [comment]
The same thing happens to me, Samsung S20 Ultra Android13

If you set only PIN or patter without fingerprint app tell "No Biometric or PIN set"
Work only when Fingerprint is registered. 

If you have register fingerprint but in phone settings disable fingerprint unlock, you can use fingerprint to open although this option is turned off in the phone.

**Comment by aashishksahu** [comment]
Hmm... This Biometric thing is giving a lot of strange behavior, I guess I need to figure out a better way to authenticate. Time for some research...

**Comment by aashishksahu** [comment]
Hi everyone! I have pushed an update with a newer authentication mechanism, please try it and let me know if any issues :)

**Comment by atikattar1104** [comment]
Hi @aashishksahu, After Long Time I Got Free Time Now. Just Saw The Latest Update. 

I Am Glad To See The New Authentication Mechanism Used In The App. Saw A Few People Online Who Were Able To Bypass Original Android Lockscreen Authentication Using Old Methods, On Newer Devices (Yes, They Have Latest Android OS). But, Most Cybersecurity Experts Do Say It Is More Difficult To Crack An App's Built-In Authentication Than Android's Built-In Lock. That's Why The New Authentication Mechanism Is Better Than Previous. 

Although The New Method Is Better, It Needs Some New Features. Like :- 

1. PIN Or Password Choice. 
2. Change Password Whenever User Wants, After Unlocking, And From A Special Page/Dialog Box. 
3. Auto-Lock As Soon As App Close/After Specific Time. 
4. Lock On/Off Switch (For Users Who Just Want To Hide Data, Than Locking It Safe). 
5. Biometric Usage On/Off Switch. 

Anyway, Great App Though.

**Comment by aashishksahu** [comment]
@atikattar1104 Thanks for the suggestions, I am planning some of them already. Also, if you'd like to work on these, I'd be happy to help you set up and build.

Let's head over to [Discussions](https://github.com/aashishksahu/SafeSpace/discussions/28#discussion-6091463) to discuss ideas :)
