### ISSUE TITLE
Add "support" for Jpeg

### ISSUE THREAD

**Issue by heschy2** [aashishksahu/SafeSpace#31]
JPGE and JPG is basucally the same thing, however the former file-suffix is not supported. In order to display .jpeg Files in SafeSpace, I have to renam them to .jpg, could support for .joeg be added?

Since it is essentially just adding a string and an or i to an if statement it should be much work right?

Note: The former statement might be totally wrong because I didn't read the source code (I just began to learn Android Programming, so this is like taking a look into the linux kernel: useless)

**Comment by heschy2** [comment]
Okay, I took a look into the source code, and in one way I was right: I dont understand it. 🤣.

But I think I found out how to solve this.

In Constants.kt 


```kotlin
        val IMAGE_EXTENSIONS = arrayOf(
            "jpg",
            "png",
            "gif",
            "webp",
            "tiff",
            "psd",
            "raw",
            "bmp",
            "svg",
            "heif"
        )
```

Would need the addition of the "jpeg" entry, right?

**Comment by aashishksahu** [comment]
Yup, you guessed it right, just added "jpeg" in the array and now it's supported. Watch out for the next update :)
