### ISSUE TITLE
Why root?

### ISSUE THREAD

**Issue by gitzila** [aashishksahu/SafeSpace#33]
Hi,
why does the app requests root access when starting the first time?
Gitzila

**Comment by aashishksahu** [comment]
Hi @gitzila That is not something I put there, maybe there's some misunderstanding, my app doesn't ask for root access, it just checks for root and warns the user of root being unsafe. Can you please post some screenshots so that I can better understand.

**Comment by aashishksahu** [comment]
Most likely this is happening because the root check tries some commands to check whether sudo is possible or not, the app doesn't actually need root as all data is anyway stored in app's internal storage.
