### ISSUE TITLE
Option to disable biometric authentication

### ISSUE THREAD

**Issue by skoshy** [aashishksahu/SafeSpace#34]
I'd like to only use a PIN to access files in Safe Space, I don't want to use biometrics as this is a shared device.

Can there be an option to disable biometrics and only use PIN?

**Comment by aashishksahu** [comment]
Hi @skoshy, thanks for reaching out, this feature is already in the [roadmap](https://github.com/aashishksahu/SafeSpace/discussions/29), and will be available in the upcoming update.
