### ISSUE TITLE
[BUG] PIN Number Starting With "0" Is Not Supported.

### ISSUE THREAD

**Issue by atikattar1104** [aashishksahu/SafeSpace#38]
In Safe Space v1.4.3, I Was Trying To Setup A PIN Code For Lock Functionality As `0XXX`. At First Stage `Set PIN`, PIN Code Is Accepted Successfully, But In Second Stage `Confirm PIN`, When Entering Same PIN For Confirmation, There Is A Edittext Error Saying `PIN Does Not Match`. 

Other PINs Works Fine Though.

**Comment by aashishksahu** [comment]
Interesting observation, thanks for opening the issue. I’ll check this.
