### ISSUE TITLE
Option to export files

### ISSUE THREAD

**Issue by erazemk** [aashishksahu/SafeSpace#4]
In the readme it says that files can be imported and exported, but I can't find the option to export files. Am I missing something?

I just imported a few random images, I haven't created any folders.

**Comment by aashishksahu** [comment]
Hi Erazemk, if you tap on the file icon, you will get the option to select multiple files as well as the option to export those files. Hope this helps, let me know in case you need further support :)

**Comment by aashishksahu** [comment]
I meant to say a single tap on the thumbnail image on the left side of the file name.

**Comment by erazemk** [comment]
Ah, that works perfectly, thank you!
