### ISSUE TITLE
Problems with version 1.4.4

### ISSUE THREAD

**Issue by atomuspilius** [aashishksahu/SafeSpace#40]
When upgrading to version 1.4.4, the old PIN code stops working.
When you roll back to the previous version, the PIN code starts working again
![Screenshot_20240309-175359_Safe_Space](https://github.com/aashishksahu/SafeSpace/assets/128164289/a611a3f2-4855-4453-af46-951b2be1c959)

**Comment by aashishksahu** [comment]
Hi @atomuspilius Thanks for pointing this out. Please set up a pin with v1.4.3 and then try to update it to [v1.4.5](https://github.com/aashishksahu/SafeSpace/blob/38-bug-pin-number-starting-with-0-is-not-supported/app/release/app-release.apk) and let me know if it works.

**Comment by aashishksahu** [comment]
Ok great, will create a new release :)
