### ISSUE TITLE
Sorting and numbers

### ISSUE THREAD

**Issue by atomuspilius** [aashishksahu/SafeSpace#44]
Greetings! Is it possible to return the sorting changes as it was before 1.4.4? 🙂
After the update, all numeric names became more randomly placed.
![Screens](https://github.com/aashishksahu/SafeSpace/assets/128164289/0a5f1393-12ff-4519-9cbf-3b6ca1b3bd10)

**Comment by aashishksahu** [comment]
The sorting looks correct to me. I tried creating files with the same names in windows and it gave me the same order.
![IMG_1692](https://github.com/aashishksahu/SafeSpace/assets/26797677/541025f3-3b81-40c4-9caf-9a8056dccb30)
