### ISSUE TITLE
app wrongly detects “rooted phone”

### ISSUE THREAD

**Issue by j-lakeman** [aashishksahu/SafeSpace#5]
I'm running just a custom OS, but my device is unrooted. This makes the app unusable for me as it quits right after the start.

**Comment by aashishksahu** [comment]
Thanks for highlighting this, unfortunately I don't have a rooted phone with me, so I would require your help, please share the following details:

* Custom ROM name and version
* Device model (brand, model, codename, if possible)
* whether magisk is installed
* can you browse the root folders using a root file manager

**Comment by j-lakeman** [comment]
>     * Custom ROM name and version
LineageOS 19 being equivalent to Android 12
>     * Device model (brand, model, codename, if possible)
Samsung Galaxy S7 / SM-G930F / herolte
>     * whether magisk is installed
negative
>     * can you browse the root folders using a root file manager
negative

**Comment by aashishksahu** [comment]
Looks like I can skip the android.os.Build.TAGS check for "test-keys" since, most roms might not have "release-keys" Tag. I am creating a branch for this fix.

**Comment by aashishksahu** [comment]
I have pushed an update for this and a test apk can be found [here](https://github.com/aashishksahu/SafeSpace/tree/5-app-wrongly-detects-rooted-phone/app/release). Please try this apk and let me know if it works for you. If it still doesn't work then most likely the "Superuser.apk" exists on your phone's system storage or superuser commands can be executed on your phone.

**Comment by j-lakeman** [comment]
Seems to work. Great job thanks!

**Comment by j-lakeman** [comment]
Maybe there could be a hint saying like "your custom ROM seems to be signed with testing keys. This is considered to be unsafe" but with the app still working.

**Comment by aashishksahu** [comment]
Seems like a good idea, I guess I can add this as a warning message.
