### ISSUE TITLE
Improving the image viewer

### ISSUE THREAD

**Issue by atomuspilius** [aashishksahu/SafeSpace#57]
Greetings! A couple of thoughts about the convenience of viewing:

1. The image viewer, in full screen, scrolls through the images not according to the selected sorting method, but according to some kind of its own script. It would be very convenient for an image viewer to scroll through the images according to the selected sorting method.

2. If you scrolled through a large number of images in the image viewer (in full-screen mode) and reached the image you want to delete, then clicking the back button will take you to the place where you started viewing. And to delete an unnecessary image, you have to scroll down the page for a long time, trying to "catch" it with your eyes among a large number of images, which is very inconvenient.

It would be great if, when scrolling through images in full-screen mode and pressing the Back button, the image you finished viewing was displayed at the top of the explorer for quick access to this image, for further actions with it.

Or (if it is easier to implement) in full-screen mode, when you click on the image, the "Delete" button appeared.

**Comment by aashishksahu** [comment]
Hi @atomuspilius, those are some good suggestions, I am currently working on a redesign with better UI and overalls. Will accommodate these as well. This will take a few months, but I am sure the new design will look good to the user and will be easier for me to maintain.
