### ISSUE TITLE
Error and crash when creating folders.

### ISSUE THREAD

**Issue by atomuspilius** [aashishksahu/SafeSpace#62]
The error occurs when creating multiple folders with a number at the beginning of the name.

When logging into the application after trying to create a second folder with a number at the beginning of the name and then exiting the application, it fails.

DivestOS 18.1, Android 11

Screen recording: 
[recording.mp4.zip](https://github.com/user-attachments/files/15966107/recording.mp4.zip)
LogCat: 
[log_safespace.txt](https://github.com/user-attachments/files/15966146/log_safespace.txt)

P.S. Thanks for the new design!

**Comment by aashishksahu** [comment]
Lol, I tested this on all types of pixel devices and on a Samsung too. I’ll look into it. Glad to see you like the redesign :)
