### ISSUE TITLE
[Feature Request] Material You design

### ISSUE THREAD

**Issue by W1zardK1ng** [aashishksahu/SafeSpace#65]
The new design of the app looks good but it will be nice to have the support for Material You coloring.

**Comment by aashishksahu** [comment]
This I can think about. Let me check if I can add this in my road map.

**Comment by aashishksahu** [comment]
How big of a requirement is this? I have tried a few things but all of them somewhat make the ui look uglier. Material you is weird with so many washed out colours and depressing grey backgrounds. I mean look at Ios/mac and windows and even gnome desktop with blur-my-shell plugin, all of them look so neat and material you looks like someone at google obsessed with colour theory went bonkers. Grey backgrounds kill the whole point of having OLED displays and the foreground colours look like some teen girl's nail art.
