### ISSUE TITLE
[Feature Request] Encrypted backup

### ISSUE THREAD

**Issue by W1zardK1ng** [aashishksahu/SafeSpace#66]
The current backup file is just a normal zip file, though its enough for having a backup but to add a layer of protection it will be good to have encrypted backup file or add a password for the backup files.

**Comment by aashishksahu** [comment]
you can export the backup and encrypt the file using GPG/AGE/Veracrypt/Cryptomator, these are well tested apps that are reliable and have stood the test of time.
