### ISSUE TITLE
[Feature Request] Renaming folders and files

### ISSUE THREAD

**Issue by atomuspilius** [aashishksahu/SafeSpace#70]
It would be very convenient if it were possible to rename folders and files. Currently, you need to create a new folder and move the contents of the folder with the old name to it. And the files have to be exported, renamed and imported again, which takes longer if it could be done inside the application.
If it is possible/not difficult to implement.

Thank you for your work! 🙏

**Comment by aashishksahu** [comment]
Will add this.
