### ISSUE TITLE
non functional scrollbar

### ISSUE THREAD

**Issue by clach04** [aashishksahu/SafeSpace#77]
For notes that have many lines, what looks like a scrollbar appears on the right hand side. This can not be grabbed and scrolled, can only drag canvas. This makes scrolling slow.Versi
Version seen 2.0.3.

Kudos on the app, neat idea!

**Comment by aashishksahu** [comment]
Thanks, let me see how I can add it.

**Comment by aashishksahu** [comment]
Hi @clach04, is this type of smooth scrolling ok for you, there is no option available by default to enable the hold and drag method of the scrollbar, it will require some custom implementation which might end up being a bit laggy. This smooth scrolling looks better in my opinion and is similar to the scrolling behavior found in other material apps.

[scrolling.webm](https://github.com/user-attachments/assets/d70d825f-5724-47b4-9777-1c2b50ac966a)

**Comment by clach04** [comment]
@aashishksahu sorry for the delay, that looks much faster for navigating around!
