### ISSUE TITLE
v2.0.3 creating new (non-empty) note shows 0 bytes on save

### ISSUE THREAD

**Issue by clach04** [aashishksahu/SafeSpace#78]
When returning to main list view. Steps.

1. Create new note.Enter
2.  Content.
3. "Go back" / save by pressing back button
4. See note name but 0 bytes file size reported

Workaround, open any note and go back to main list view.

**Comment by aashishksahu** [comment]
Yup, I know this one, still trying to figure it out.

**Comment by clach04** [comment]
Confirmed fixed/resolved in https://github.com/aashishksahu/SafeSpace/releases/tag/2.0.5
