### ISSUE TITLE
[Feature Request] Exporting backup progress notification

### ISSUE THREAD

**Issue by UltraFeed** [aashishksahu/SafeSpace#83]
Add exporting bacup into zip progress notification, this would be helpful

**Comment by aashishksahu** [comment]
@starry-shivam hey man! Can you please take this one if you have the bandwidth :)

**Comment by starry-shivam** [comment]
Hello!

> Can you please take this one if you have the bandwidth :)

Alright, I'll try whenever i get some time.

**Comment by aashishksahu** [comment]
> Hello!
> 
> > Can you please take this one if you have the bandwidth :)
> 
> Alright, I'll try whenever i get some time.

Thanks :)

**Comment by aashishksahu** [comment]
Thanks @starry-shivam for the PR, your'e a real master of this :)
