### ISSUE TITLE
easy jumping to end of note file

### ISSUE THREAD

**Issue by clach04** [aashishksahu/SafeSpace#85]
Any ideas on how to get to the end of a large note?

I tried out https://github.com/aashishksahu/SafeSpace/releases/tag/2.0.4 (from fdroid, not this specific apk) andwith smooth scrolling support https://github.com/aashishksahu/SafeSpace/issues/77, large notes ~128Kb take a long time to scroll to the end.

Low priority! :-)

**Comment by clach04** [comment]
Cross ref to https://github.com/aashishksahu/SafeSpace/issues/86

**Comment by aashishksahu** [comment]
I can add a button to go to the end of the file.
