### ISSUE TITLE
Max file size for notes

### ISSUE THREAD

**Issue by clach04** [aashishksahu/SafeSpace#86]
Are there restrictions on maximum length/size of notes?

Copy / paste something larger than 128Kb, results in truncation.

However it is possible to edit the note and add to the end. On my android 10 device this very slow.

Low priority.

**Comment by aashishksahu** [comment]
@clach04 This looks like the size of your clipboard is limited to 128kb. Does pasting in other apps also result in truncation?

**Comment by clach04** [comment]
Sorry for the delay, been a busy week and it took a while to try a few apps out.

Test method. Using SciteQt for Android open 165Kb file with ~4202 lines. Press and hold to select something, then select-all from pop up menu (that I believe is the system menu for selecting, copying, sharing, sending to, pasting, etc.)  Then Copy. Them in other apps press and hold to then use paste (again system paste, not keyboard or application specific paste).


## what works as expected

  * SciteQt
  * Acode
  * Mozilla Firefox with a webpage open with a simple form with a text entry field. Specifically 

## what does not work

  * this app
  * Markor
  * bill the farmer Editor application

I wonder if this is specific to the editor control being used?

TODO add links to apps.

**Comment by aashishksahu** [comment]
Hi @clach04 , Thanks for the detailed information, the apps that work, such as SciteQT, Acode and Firefox are built using QT, Apache Cordova and lot of custom stuff in firefox, respectively. And the apps that don't work are android native. So, you could be right, it could be a limitation of the EditText component that is available in android native SDK. So, it seems like a limitation of the available material ui component.

**Comment by clach04** [comment]
Thanks for the quick analysis, https://developer.android.com/reference/android/widget/EditText I'm guessing? Annoyingly no doca on limits in there 😿

**Comment by aashishksahu** [comment]
yes this one. Android documentation sometimes feels incomplete.

**Comment by clach04** [comment]
I'm not an Android developer so what follows is a lot of supposition  based on some observations.

bill the farmer's editor can open. And edit the ~165Kb file, but pasting truncates. This maybe a paste limitation (or bug) in Android EditText https://developer.android.com/reference/android/widget/EditText

**Comment by aashishksahu** [comment]
I tried in my latest build and I am able to copy and paste large text, please try again and let me know if the issue remains. This could be some kind of device limitation for native android apps which varies device to device.

**Comment by clach04** [comment]
Just tried 2.0.5 on my Android 10 phone mostly same behavior with truncation which was expected :-)

One difference one seeing is that copying more than 128Kb in safe notes is that I now get a toast message that makes things clear:

Maximum size of text that can be 
copied exceeded. Only first 128 KB 
copied to clipboard.

I think we can close this as depends on device is, may be 128Kb.

Out of curiosity what version of Android are you using @aashishksahu ?

**Comment by aashishksahu** [comment]
Well, I do all my development and testing on a pixel emulator, that way I can ensure support on multiple versions.
