### ISSUE TITLE
light theme/scheme hard to read

### ISSUE THREAD

**Issue by clach04** [aashishksahu/SafeSpace#87]
The bottom virtual buttons for home and back are very difficult to see/read.

Dark theme is fine.

**Comment by clach04** [comment]
![Screenshot_20240811-112608_Safe Space](https://github.com/user-attachments/assets/ac9c0bbe-90c7-4d7a-9722-c874406ab1b5)

**Comment by clach04** [comment]
Firefox screenshot for comparison, see bottom images.
![Screenshot_20240811-112742_Firefox](https://github.com/user-attachments/assets/60c3c0b4-7ca1-4953-a0f2-a9365fc89a2c)

**Comment by aashishksahu** [comment]
Hmm… ok let me check this.

**Comment by clach04** [comment]
Confirmed fixed/resolved in https://github.com/aashishksahu/SafeSpace/releases/tag/2.0.5
