### ISSUE TITLE
[Feature Request] Improve PDF viewing with native text renderring, selectabilty and bookmarking

### ISSUE THREAD

**Issue by uberstar100** [aashishksahu/SafeSpace#95]
I'm not sure if the current PDF viewer implementation is itself the limitation here and that an entirely new PDF viewer engine would be needed for this, but I'd love it if the app's PDF viewer could dynamically scale (and that the text also becomes selectable).

I think this was briefly mentioned here:
https://github.com/aashishksahu/SafeSpace/issues/47#issuecomment-2014504734

It would also improve the app experience a bit if the app had an option to save the last viewed PDF page as a bookmark, and jump to the bookmarked page if the PDF file were to be opened again.

**Comment by aashishksahu** [comment]
I really want to do this but, I am yet to find a suitable library that can make pdfs more fun, most libraries are either old and not maintained anymore or they have vulnerabilities. Due to time and resource crunch I cannot implement a custom solution also, so yeah it’s a lack of resources I guess.
