### ISSUE TITLE
[Feature request] Import files with date

### ISSUE THREAD

**Issue by DionKill** [aashishksahu/SafeSpace#98]
I've noticed that in pretty much every app (this one included) that allows you to encrypt your files, it always imports them without the original date.
![Screenshot_20241009_125312](https://github.com/user-attachments/assets/b39f42f3-2b42-4e77-a076-195724793e81)
![Screenshot_20241009_125352](https://github.com/user-attachments/assets/1da3abf6-290c-446e-8f80-f8dbce5ac7bd)

If I have a picture that was took, let's say, in 2021, it'll be imported but shows it's date as the moment it was imported. If I instead were to create a zip with pictures taken in 2021 using a file manager, and then I extract it, the dates stay the same, but it obviously isn't encrypted.

Is there a way to either:
1. Add files with the original date;
2. Add files with the date it was imported, but the importing is sorted by date instead of being random, so that the oldest gets imported first and I can still sort by date.

I would love for this to be implemented, also I wish to know why the first one is (again I'm assuming) impossible to do.

**Comment by DionKill** [comment]
Yeah I was assuming it was impossible to import the date specifically, but is it possible to import by date so that I can still sort by date?

**Comment by aashishksahu** [comment]
Hi @DionKill Unfortunately it's not possible to get the date of the old file because importing basically means copying. A new copy is created everytime you import.

**Comment by DionKill** [comment]
I see. But is it possible to import the files starting from the oldest one first? So that the new copies are still ordered by date?
I mean if I have a picture from 2021 and one from 2022 it imports the one from 2021 first and then the one from 2022.

**Comment by aashishksahu** [comment]
Well, I tried this but for some reason I couldn't find a way to get the last modified timestamp of the original file. Apparently, both content provider and File apis don't return the timestamp

**Comment by aashishksahu** [comment]
Yes, you can just sort by name in that case.
